version: '3.8'

services:
  web:
    image: obi1o/code-spark:latest
    build: .
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - REDIS_CONNECTION=redis:6379
      - ConnectionStrings__Redis=redis:6379
      # EF Core connection string injected as env var:
      - ConnectionStrings__Sql=Server=mssql,1433;Database=DataStoreDB;User Id=sa;Password=Fast192837465;TrustServerCertificate=True;MultipleActiveResultSets=True
    depends_on:
      - redis
      - mssql
    volumes:
      - ./dataprotection-keys:/keys
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Fast192837465"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network

volumes:
  redis-data:
  mssql-data:

networks:
  app-network:
